# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Perspective Project
email: curious.robot@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of life experiences from the
  perspectives of everyday people.
baseurl: "/perspectiveproject" # the subpath of your site, e.g. /blog
url: "http://curious-robot.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  curious-robot

# Build settings
markdown: kramdown
