title: The Perspective Project
description: A collection of life experiences from the perspectives of everyday people.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://perspective.thecuriousrobot.com" # the base hostname & protocol for your site
